### ISSUE TITLE
مشکل در دانلود از کولب

### ISSUE THREAD

**Issue by mohsenhrt** [J-Yaghoubi/iran_stock#1]
سلام وتشکر از این مخزن، سوالی داشتم که چرا از طریق کولب نمیشه اطلاعات سهام رو دانلود کرد؟ یعنی همه چی درست نصب میشه ولی اطلاعات رو نمیتونه از سایت بخونه و خطای اتصال میده
بازم تشکر

**Comment by J-Yaghoubi** [comment]
> 

با عرض سلام، موضوعی که فرمودید بررسی شد. ابزار به خوبی و بدون مشکل کار می کند و دلیل اینکه در کولب قادر به استفاده از آن نیستید به این موضوع مربوط می شود که در حال حاضر سایت tsetmc دسترسی از طریق آی پی های خارجی را مسدود کرده است و لذا نمی توان از طریق کولب یا هر ابزار دیگری که در خارج از کشور قرار دارد به این سایت دسترسی پیدا کرده و داده دریافت نمود. امیدواریم محدودیتی که اعمال شده است موقتی باشد و به زودی رفع گردد. بنابراین با توجه به اینکه مشکل از سمت ابزار نیست، متاسفانه رفع آن نیز از عهده ما خارج است. پیشنهاد می شود فعلا به طریقی عمل بفرمایید که اتصال از طریق ایپی داخلی صورت بگیرد. این کار می تواند از طریق سیستم شخصی و یا وی پی ان داخلی انجام گردد. باتشکر

**Comment by J-Yaghoubi** [comment]
> سلام وتشکر از این مخزن، سوالی داشتم که چرا از طریق کولب نمیشه اطلاعات سهام رو دانلود کرد؟ یعنی همه چی درست نصب میشه ولی اطلاعات رو نمیتونه از سایت بخونه و خطای اتصال میده بازم تشکر


با عرض سلام، موضوعی که فرمودید بررسی شد. ابزار به خوبی و بدون مشکل کار می کند و دلیل اینکه در کولب قادر به استفاده از آن نیستید به این موضوع مربوط می شود که در حال حاضر سایت tsetmc دسترسی از طریق آی پی های خارجی را مسدود کرده است و لذا نمی توان از طریق کولب یا هر ابزار دیگری که در خارج از کشور قرار دارد به این سایت دسترسی پیدا کرده و داده دریافت نمود. امیدواریم محدودیتی که اعمال شده است موقتی باشد و به زودی رفع گردد. بنابراین با توجه به اینکه مشکل از سمت ابزار نیست، متاسفانه رفع آن نیز از عهده ما خارج است. پیشنهاد می شود فعلا به طریقی عمل بفرمایید که اتصال از طریق ایپی داخلی صورت بگیرد. این کار می تواند از طریق سیستم شخصی و یا وی پی ان داخلی انجام گردد. باتشکر
